<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "stoweb_photo"
 *
 * Auto generated by Extension Builder 2021-05-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'PhoSTO',
    'description' => 'Projet phototèque DAWIN 20-21 de l\'équipe STOWeb',
    'category' => 'plugin',
    'author' => 'Titouan LEVET, Matthias CATHELINEAU, Frédéric ALLEGRET, Valerian LAFFERAYRIE, Thomas CHABROL',
    'author_email' => 'lev.titouan@gmail.com, mat.cathelineau@gmail.com, frederic.allegret@hotmail.fr, lafferayrie.val@gmail.com, thomas.chabrol3@gmail.com',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
